# Geo helper is the module collection that does all the transformation related calculation.
# The parameters below specifies some behaivors of the module 
geohelper:
  # base level and top level defines the behavoir of the dbloader. For any given feature, 
  # the maximum level to store is the base level, the minimum level to store is the 
  # top level. If a feature is too large to store into a single top level tile, it will
  # be stored in all overlapping top level tiles
  base level: 13
  top level: 4

  # Num covering limit defines the maximum number of tiles allowed for a feature to store
  # in a level. If the current level cannot hold the featuer within the number of tiles limit
  # defined here, it will seek a higher level covering, which esentially reduce the level by 1.
  # NOTE: this parameter does not limit the number of tiles for the top level. 
  num covering limit: 3

dbhelper:
  # list of node: ['127.0.0.1', '138.67.187.226', '138.67.187.225', '138.67.187.149', '138.67.187.217', '138.67.186.219', '138.67.187.191', '138.67.187.221', '138.67.186.205']
  # key space: 'global01'
  # truncate table when start: false

main:
  # load to master: true
  # duplication method: true
  # cutting method: true
