//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

GeolocationService_getFeatures_args = function(args) {
  this.lBox = null;
  this.rBox = null;
  this.bBox = null;
  this.tBox = null;
  if (args) {
    if (args.lBox !== undefined) {
      this.lBox = args.lBox;
    }
    if (args.rBox !== undefined) {
      this.rBox = args.rBox;
    }
    if (args.bBox !== undefined) {
      this.bBox = args.bBox;
    }
    if (args.tBox !== undefined) {
      this.tBox = args.tBox;
    }
  }
};
GeolocationService_getFeatures_args.prototype = {};
GeolocationService_getFeatures_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.DOUBLE) {
        this.lBox = input.readDouble().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.DOUBLE) {
        this.rBox = input.readDouble().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.DOUBLE) {
        this.bBox = input.readDouble().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.DOUBLE) {
        this.tBox = input.readDouble().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GeolocationService_getFeatures_args.prototype.write = function(output) {
  output.writeStructBegin('GeolocationService_getFeatures_args');
  if (this.lBox !== null && this.lBox !== undefined) {
    output.writeFieldBegin('lBox', Thrift.Type.DOUBLE, 1);
    output.writeDouble(this.lBox);
    output.writeFieldEnd();
  }
  if (this.rBox !== null && this.rBox !== undefined) {
    output.writeFieldBegin('rBox', Thrift.Type.DOUBLE, 2);
    output.writeDouble(this.rBox);
    output.writeFieldEnd();
  }
  if (this.bBox !== null && this.bBox !== undefined) {
    output.writeFieldBegin('bBox', Thrift.Type.DOUBLE, 3);
    output.writeDouble(this.bBox);
    output.writeFieldEnd();
  }
  if (this.tBox !== null && this.tBox !== undefined) {
    output.writeFieldBegin('tBox', Thrift.Type.DOUBLE, 4);
    output.writeDouble(this.tBox);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GeolocationService_getFeatures_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
GeolocationService_getFeatures_result.prototype = {};
GeolocationService_getFeatures_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new Feature();
          elem6.read(input);
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GeolocationService_getFeatures_result.prototype.write = function(output) {
  output.writeStructBegin('GeolocationService_getFeatures_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

GeolocationServiceClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
GeolocationServiceClient.prototype = {};
GeolocationServiceClient.prototype.getFeatures = function(lBox, rBox, bBox, tBox) {
  this.send_getFeatures(lBox, rBox, bBox, tBox);
  return this.recv_getFeatures();
};

GeolocationServiceClient.prototype.send_getFeatures = function(lBox, rBox, bBox, tBox) {
  this.output.writeMessageBegin('getFeatures', Thrift.MessageType.CALL, this.seqid);
  var args = new GeolocationService_getFeatures_args();
  args.lBox = lBox;
  args.rBox = rBox;
  args.bBox = bBox;
  args.tBox = tBox;
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush();
};

GeolocationServiceClient.prototype.recv_getFeatures = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new GeolocationService_getFeatures_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'getFeatures failed: unknown result';
};
